/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProgrammableMultiSigWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addOwner"
      | "addWhitelistedRecipient"
      | "approveTransaction"
      | "approved"
      | "cancelTransaction"
      | "changeThreshold"
      | "dailyLimit"
      | "executeTransaction"
      | "freezeWallet"
      | "getDailyLimit"
      | "getRemainingDailyLimit"
      | "getSpentToday"
      | "getTransactionCount"
      | "highValueThreshold"
      | "isFrozen"
      | "isOwner"
      | "isWhitelistedRecipient"
      | "lastResetTimestamp"
      | "ownerCount"
      | "owners"
      | "removeOwner"
      | "removeWhitelistedRecipient"
      | "revokeApproval"
      | "setDailyLimit"
      | "setHighValueThreshold"
      | "setTimelockDuration"
      | "spentToday"
      | "submitTransaction"
      | "threshold"
      | "timelockDuration"
      | "transactions"
      | "unfreezeWallet"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApprovalRevoked"
      | "DailyLimitChanged"
      | "Deposit"
      | "HighValueThresholdChanged"
      | "OwnerAdded"
      | "OwnerRemoved"
      | "ThresholdChanged"
      | "TransactionApproved"
      | "TransactionCancelled"
      | "TransactionExecuted"
      | "TransactionSubmitted"
      | "WalletFrozen"
      | "WalletUnfrozen"
      | "WhitelistedRecipientAdded"
      | "WhitelistedRecipientRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addWhitelistedRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "freezeWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDailyLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingDailyLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSpentToday",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "highValueThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isFrozen", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelistedRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastResetTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ownerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "owners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeWhitelistedRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeApproval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDailyLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHighValueThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimelockDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "spentToday",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitTransaction",
    values: [AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "threshold", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "timelockDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unfreezeWallet",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addWhitelistedRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approved", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dailyLimit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSpentToday",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "highValueThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isFrozen", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelistedRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastResetTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeWhitelistedRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHighValueThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimelockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "spentToday", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "threshold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "timelockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unfreezeWallet",
    data: BytesLike
  ): Result;
}

export namespace ApprovalRevokedEvent {
  export type InputTuple = [txId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [txId: bigint, owner: string];
  export interface OutputObject {
    txId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyLimitChangedEvent {
  export type InputTuple = [newDailyLimit: BigNumberish];
  export type OutputTuple = [newDailyLimit: bigint];
  export interface OutputObject {
    newDailyLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    sender: AddressLike,
    amount: BigNumberish,
    balance: BigNumberish
  ];
  export type OutputTuple = [sender: string, amount: bigint, balance: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
    balance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HighValueThresholdChangedEvent {
  export type InputTuple = [newHighValueThreshold: BigNumberish];
  export type OutputTuple = [newHighValueThreshold: bigint];
  export interface OutputObject {
    newHighValueThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerAddedEvent {
  export type InputTuple = [owner: AddressLike];
  export type OutputTuple = [owner: string];
  export interface OutputObject {
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerRemovedEvent {
  export type InputTuple = [owner: AddressLike];
  export type OutputTuple = [owner: string];
  export interface OutputObject {
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdChangedEvent {
  export type InputTuple = [newThreshold: BigNumberish];
  export type OutputTuple = [newThreshold: bigint];
  export interface OutputObject {
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionApprovedEvent {
  export type InputTuple = [txId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [txId: bigint, owner: string];
  export interface OutputObject {
    txId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionCancelledEvent {
  export type InputTuple = [txId: BigNumberish];
  export type OutputTuple = [txId: bigint];
  export interface OutputObject {
    txId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionExecutedEvent {
  export type InputTuple = [txId: BigNumberish];
  export type OutputTuple = [txId: bigint];
  export interface OutputObject {
    txId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionSubmittedEvent {
  export type InputTuple = [
    txId: BigNumberish,
    proposer: AddressLike,
    destination: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [
    txId: bigint,
    proposer: string,
    destination: string,
    value: bigint
  ];
  export interface OutputObject {
    txId: bigint;
    proposer: string;
    destination: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletFrozenEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletUnfrozenEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistedRecipientAddedEvent {
  export type InputTuple = [recipient: AddressLike];
  export type OutputTuple = [recipient: string];
  export interface OutputObject {
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistedRecipientRemovedEvent {
  export type InputTuple = [recipient: AddressLike];
  export type OutputTuple = [recipient: string];
  export interface OutputObject {
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProgrammableMultiSigWallet extends BaseContract {
  connect(runner?: ContractRunner | null): ProgrammableMultiSigWallet;
  waitForDeployment(): Promise<this>;

  interface: ProgrammableMultiSigWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addOwner: TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;

  addWhitelistedRecipient: TypedContractMethod<
    [_recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  approveTransaction: TypedContractMethod<
    [_txId: BigNumberish],
    [void],
    "nonpayable"
  >;

  approved: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  cancelTransaction: TypedContractMethod<
    [_txId: BigNumberish],
    [void],
    "nonpayable"
  >;

  changeThreshold: TypedContractMethod<
    [_newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  dailyLimit: TypedContractMethod<[], [bigint], "view">;

  executeTransaction: TypedContractMethod<
    [_txId: BigNumberish],
    [void],
    "nonpayable"
  >;

  freezeWallet: TypedContractMethod<[], [void], "nonpayable">;

  getDailyLimit: TypedContractMethod<[], [bigint], "view">;

  getRemainingDailyLimit: TypedContractMethod<[], [bigint], "view">;

  getSpentToday: TypedContractMethod<[], [bigint], "view">;

  getTransactionCount: TypedContractMethod<[], [bigint], "view">;

  highValueThreshold: TypedContractMethod<[], [bigint], "view">;

  isFrozen: TypedContractMethod<[], [boolean], "view">;

  isOwner: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isWhitelistedRecipient: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  lastResetTimestamp: TypedContractMethod<[], [bigint], "view">;

  ownerCount: TypedContractMethod<[], [bigint], "view">;

  owners: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  removeOwner: TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;

  removeWhitelistedRecipient: TypedContractMethod<
    [_recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeApproval: TypedContractMethod<
    [_txId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDailyLimit: TypedContractMethod<
    [_newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHighValueThreshold: TypedContractMethod<
    [_newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTimelockDuration: TypedContractMethod<
    [_newDuration: BigNumberish],
    [void],
    "nonpayable"
  >;

  spentToday: TypedContractMethod<[], [bigint], "view">;

  submitTransaction: TypedContractMethod<
    [
      _destination: AddressLike,
      _value: BigNumberish,
      _data: BytesLike,
      _expiryDuration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  threshold: TypedContractMethod<[], [bigint], "view">;

  timelockDuration: TypedContractMethod<[], [bigint], "view">;

  transactions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        destination: string;
        value: bigint;
        data: string;
        proposer: string;
        timestamp: bigint;
        expiryTimestamp: bigint;
        executableAt: bigint;
        approvalCount: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  unfreezeWallet: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addOwner"
  ): TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addWhitelistedRecipient"
  ): TypedContractMethod<[_recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveTransaction"
  ): TypedContractMethod<[_txId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approved"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelTransaction"
  ): TypedContractMethod<[_txId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeThreshold"
  ): TypedContractMethod<[_newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dailyLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeTransaction"
  ): TypedContractMethod<[_txId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "freezeWallet"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDailyLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRemainingDailyLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSpentToday"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTransactionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "highValueThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isFrozen"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOwner"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWhitelistedRecipient"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastResetTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ownerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owners"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "removeOwner"
  ): TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeWhitelistedRecipient"
  ): TypedContractMethod<[_recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeApproval"
  ): TypedContractMethod<[_txId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDailyLimit"
  ): TypedContractMethod<[_newLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHighValueThreshold"
  ): TypedContractMethod<[_newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTimelockDuration"
  ): TypedContractMethod<[_newDuration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "spentToday"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitTransaction"
  ): TypedContractMethod<
    [
      _destination: AddressLike,
      _value: BigNumberish,
      _data: BytesLike,
      _expiryDuration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "threshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "timelockDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transactions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        destination: string;
        value: bigint;
        data: string;
        proposer: string;
        timestamp: bigint;
        expiryTimestamp: bigint;
        executableAt: bigint;
        approvalCount: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "unfreezeWallet"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ApprovalRevoked"
  ): TypedContractEvent<
    ApprovalRevokedEvent.InputTuple,
    ApprovalRevokedEvent.OutputTuple,
    ApprovalRevokedEvent.OutputObject
  >;
  getEvent(
    key: "DailyLimitChanged"
  ): TypedContractEvent<
    DailyLimitChangedEvent.InputTuple,
    DailyLimitChangedEvent.OutputTuple,
    DailyLimitChangedEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "HighValueThresholdChanged"
  ): TypedContractEvent<
    HighValueThresholdChangedEvent.InputTuple,
    HighValueThresholdChangedEvent.OutputTuple,
    HighValueThresholdChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnerAdded"
  ): TypedContractEvent<
    OwnerAddedEvent.InputTuple,
    OwnerAddedEvent.OutputTuple,
    OwnerAddedEvent.OutputObject
  >;
  getEvent(
    key: "OwnerRemoved"
  ): TypedContractEvent<
    OwnerRemovedEvent.InputTuple,
    OwnerRemovedEvent.OutputTuple,
    OwnerRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdChanged"
  ): TypedContractEvent<
    ThresholdChangedEvent.InputTuple,
    ThresholdChangedEvent.OutputTuple,
    ThresholdChangedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionApproved"
  ): TypedContractEvent<
    TransactionApprovedEvent.InputTuple,
    TransactionApprovedEvent.OutputTuple,
    TransactionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionCancelled"
  ): TypedContractEvent<
    TransactionCancelledEvent.InputTuple,
    TransactionCancelledEvent.OutputTuple,
    TransactionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TransactionExecuted"
  ): TypedContractEvent<
    TransactionExecutedEvent.InputTuple,
    TransactionExecutedEvent.OutputTuple,
    TransactionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionSubmitted"
  ): TypedContractEvent<
    TransactionSubmittedEvent.InputTuple,
    TransactionSubmittedEvent.OutputTuple,
    TransactionSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "WalletFrozen"
  ): TypedContractEvent<
    WalletFrozenEvent.InputTuple,
    WalletFrozenEvent.OutputTuple,
    WalletFrozenEvent.OutputObject
  >;
  getEvent(
    key: "WalletUnfrozen"
  ): TypedContractEvent<
    WalletUnfrozenEvent.InputTuple,
    WalletUnfrozenEvent.OutputTuple,
    WalletUnfrozenEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistedRecipientAdded"
  ): TypedContractEvent<
    WhitelistedRecipientAddedEvent.InputTuple,
    WhitelistedRecipientAddedEvent.OutputTuple,
    WhitelistedRecipientAddedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistedRecipientRemoved"
  ): TypedContractEvent<
    WhitelistedRecipientRemovedEvent.InputTuple,
    WhitelistedRecipientRemovedEvent.OutputTuple,
    WhitelistedRecipientRemovedEvent.OutputObject
  >;

  filters: {
    "ApprovalRevoked(uint256,address)": TypedContractEvent<
      ApprovalRevokedEvent.InputTuple,
      ApprovalRevokedEvent.OutputTuple,
      ApprovalRevokedEvent.OutputObject
    >;
    ApprovalRevoked: TypedContractEvent<
      ApprovalRevokedEvent.InputTuple,
      ApprovalRevokedEvent.OutputTuple,
      ApprovalRevokedEvent.OutputObject
    >;

    "DailyLimitChanged(uint256)": TypedContractEvent<
      DailyLimitChangedEvent.InputTuple,
      DailyLimitChangedEvent.OutputTuple,
      DailyLimitChangedEvent.OutputObject
    >;
    DailyLimitChanged: TypedContractEvent<
      DailyLimitChangedEvent.InputTuple,
      DailyLimitChangedEvent.OutputTuple,
      DailyLimitChangedEvent.OutputObject
    >;

    "Deposit(address,uint256,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "HighValueThresholdChanged(uint256)": TypedContractEvent<
      HighValueThresholdChangedEvent.InputTuple,
      HighValueThresholdChangedEvent.OutputTuple,
      HighValueThresholdChangedEvent.OutputObject
    >;
    HighValueThresholdChanged: TypedContractEvent<
      HighValueThresholdChangedEvent.InputTuple,
      HighValueThresholdChangedEvent.OutputTuple,
      HighValueThresholdChangedEvent.OutputObject
    >;

    "OwnerAdded(address)": TypedContractEvent<
      OwnerAddedEvent.InputTuple,
      OwnerAddedEvent.OutputTuple,
      OwnerAddedEvent.OutputObject
    >;
    OwnerAdded: TypedContractEvent<
      OwnerAddedEvent.InputTuple,
      OwnerAddedEvent.OutputTuple,
      OwnerAddedEvent.OutputObject
    >;

    "OwnerRemoved(address)": TypedContractEvent<
      OwnerRemovedEvent.InputTuple,
      OwnerRemovedEvent.OutputTuple,
      OwnerRemovedEvent.OutputObject
    >;
    OwnerRemoved: TypedContractEvent<
      OwnerRemovedEvent.InputTuple,
      OwnerRemovedEvent.OutputTuple,
      OwnerRemovedEvent.OutputObject
    >;

    "ThresholdChanged(uint256)": TypedContractEvent<
      ThresholdChangedEvent.InputTuple,
      ThresholdChangedEvent.OutputTuple,
      ThresholdChangedEvent.OutputObject
    >;
    ThresholdChanged: TypedContractEvent<
      ThresholdChangedEvent.InputTuple,
      ThresholdChangedEvent.OutputTuple,
      ThresholdChangedEvent.OutputObject
    >;

    "TransactionApproved(uint256,address)": TypedContractEvent<
      TransactionApprovedEvent.InputTuple,
      TransactionApprovedEvent.OutputTuple,
      TransactionApprovedEvent.OutputObject
    >;
    TransactionApproved: TypedContractEvent<
      TransactionApprovedEvent.InputTuple,
      TransactionApprovedEvent.OutputTuple,
      TransactionApprovedEvent.OutputObject
    >;

    "TransactionCancelled(uint256)": TypedContractEvent<
      TransactionCancelledEvent.InputTuple,
      TransactionCancelledEvent.OutputTuple,
      TransactionCancelledEvent.OutputObject
    >;
    TransactionCancelled: TypedContractEvent<
      TransactionCancelledEvent.InputTuple,
      TransactionCancelledEvent.OutputTuple,
      TransactionCancelledEvent.OutputObject
    >;

    "TransactionExecuted(uint256)": TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;
    TransactionExecuted: TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;

    "TransactionSubmitted(uint256,address,address,uint256)": TypedContractEvent<
      TransactionSubmittedEvent.InputTuple,
      TransactionSubmittedEvent.OutputTuple,
      TransactionSubmittedEvent.OutputObject
    >;
    TransactionSubmitted: TypedContractEvent<
      TransactionSubmittedEvent.InputTuple,
      TransactionSubmittedEvent.OutputTuple,
      TransactionSubmittedEvent.OutputObject
    >;

    "WalletFrozen()": TypedContractEvent<
      WalletFrozenEvent.InputTuple,
      WalletFrozenEvent.OutputTuple,
      WalletFrozenEvent.OutputObject
    >;
    WalletFrozen: TypedContractEvent<
      WalletFrozenEvent.InputTuple,
      WalletFrozenEvent.OutputTuple,
      WalletFrozenEvent.OutputObject
    >;

    "WalletUnfrozen()": TypedContractEvent<
      WalletUnfrozenEvent.InputTuple,
      WalletUnfrozenEvent.OutputTuple,
      WalletUnfrozenEvent.OutputObject
    >;
    WalletUnfrozen: TypedContractEvent<
      WalletUnfrozenEvent.InputTuple,
      WalletUnfrozenEvent.OutputTuple,
      WalletUnfrozenEvent.OutputObject
    >;

    "WhitelistedRecipientAdded(address)": TypedContractEvent<
      WhitelistedRecipientAddedEvent.InputTuple,
      WhitelistedRecipientAddedEvent.OutputTuple,
      WhitelistedRecipientAddedEvent.OutputObject
    >;
    WhitelistedRecipientAdded: TypedContractEvent<
      WhitelistedRecipientAddedEvent.InputTuple,
      WhitelistedRecipientAddedEvent.OutputTuple,
      WhitelistedRecipientAddedEvent.OutputObject
    >;

    "WhitelistedRecipientRemoved(address)": TypedContractEvent<
      WhitelistedRecipientRemovedEvent.InputTuple,
      WhitelistedRecipientRemovedEvent.OutputTuple,
      WhitelistedRecipientRemovedEvent.OutputObject
    >;
    WhitelistedRecipientRemoved: TypedContractEvent<
      WhitelistedRecipientRemovedEvent.InputTuple,
      WhitelistedRecipientRemovedEvent.OutputTuple,
      WhitelistedRecipientRemovedEvent.OutputObject
    >;
  };
}
